### ISSUE TITLE
Image not found, from the deployment

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#66] opened 2021-08-28 07:56 UTC
The yaml doesn't match the text.

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#quickstart

```console
$ docker pull quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/master/docs/deployment.md

`kubectl get deploy nfs-provisioner -o yaml | sed "s|quay.io/external_storage/nfs-ganesha-server-and-provisioner:latest|k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0|" | kubectl replace -f -`

**Comment by consideRatio** [comment] 2021-08-28 11:26
This is a duplicate of #46.

This helm chart is available in kvaps Helm repo atm, not yet officially packaged directly, but soon perhaps: #65.

Functional images are listed in this repos helm chart's values.yaml file.

**Comment by afbjorklund** [comment] 2021-08-28 11:59
Didn't use helm, though.

**Closed as completed** 2022-01-25 13:24 UTC
Labels: lifecycle/rotten
